[[pages]]
name = "Home"
icon = "ğŸ "
path = "pages/page1.py"

[[pages]]
name = "Analyse ETF"
icon = "ğŸ“Š"
path = "pages/analyse_graphique_app.py"

[[pages]]
name = "Prediction and Training"
icon = "ğŸ§ "
path = "pages/prediction_app.py"

[[pages]]
name = "MagistrAssistant "
icon = "âš™ï¸"
path = "pages/genai_app.py"